'use strict';

const fs   = require('fs');
const os   = require('os');
const path = require('path');

// Module under test.
// Per-user-story test tasks (US-01-TASK-TEST-01, US-02-TASK-TEST-01, etc.) will
// add real assertions inside these describe blocks as the implementation tasks
// land. This file is intentionally a scaffold — it contains only it.todo()
// placeholders so that `npx jest` exits 0 and reports todos rather than
// complaining "Your test suite must contain at least one test".
const ledger = require('../../lib/execution-ledger');

// ---------------------------------------------------------------------------
// open
// ---------------------------------------------------------------------------

describe('execution-ledger — open', () => {
  let tmpDir;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'led-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('creates a single running entry', () => {
    // Arrange: tmpDir is a fresh empty directory (set up in beforeEach)
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');

    // Act
    ledger.open(tmpDir, prefix, 'test-agent', 'phase1', 'haiku', 1);

    // Assert: ledger file contains exactly one entry with status 'running'
    const entries = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    expect(entries).toHaveLength(1);
    expect(entries[0].status).toBe('running');
  });

  it('records a JS ISO-8601 UTC started_at timestamp', () => {
    // Arrange: tmpDir is a fresh empty directory (set up in beforeEach)
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');

    // Act
    ledger.open(tmpDir, prefix, 'test-agent', 'phase1', 'haiku', 1);

    // Assert: started_at matches ISO-8601 UTC format generated by JavaScript
    const entries = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    expect(entries[0].started_at).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/);
  });

  it.todo('exits non-zero (fail-closed) when a lock cannot be acquired');

  it('exits non-zero (fail-closed) when the ledger file is corrupt', () => {
    // Arrange: write a malformed (unparseable, non-empty) JSON ledger
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');
    fs.writeFileSync(ledgerFile, '{not valid json');

    // Act & Assert: open() throws — the caller hard-stops rather than starting the activity
    expect(() => ledger.open(tmpDir, prefix, 'test-agent', 'phase1', 'haiku', 1)).toThrow();
  });

  it.todo('open() result JSON is deterministically structured');
});

// ---------------------------------------------------------------------------
// close
// ---------------------------------------------------------------------------

describe('execution-ledger — close', () => {
  let tmpDir;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'led-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it.todo('sets status to done and records completed_at');

  it('preserves an existing positive phase_delta_tokens when tokens omitted', () => {
    // Arrange: open an entry, then manually set phase_delta_tokens to a positive value
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');
    ledger.open(tmpDir, prefix, 'test-agent', 'phase1', 'haiku', 1);
    const entries = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    entries[0].phase_delta_tokens = 1234;
    ledger._writeLedger(ledgerFile, entries);

    // Act: close with null tokens (simulates --tokens being omitted)
    ledger.close(tmpDir, prefix, 'test-agent', null, 1);

    // Assert: phase_delta_tokens is preserved and status is 'done'
    const result = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    expect(result[0].phase_delta_tokens).toBe(1234);
    expect(result[0].status).toBe('done');
  });

  it.todo('null never overwrites a positive phase_delta_tokens value');
  it.todo('rejects --tokens of 0 with a non-zero exit and writes nothing');
  it.todo('rejects a negative --tokens value with a non-zero exit and writes nothing');

  it('fails for a nonexistent (never-opened) operation_id', () => {
    // Arrange: fresh empty directory (set up in beforeEach); no open() call made

    // Act & Assert: close must throw when no entry has ever been opened
    expect(() => ledger.close(tmpDir, 'FTR-999', 'ghost', null, 1)).toThrow();

    // Assert: no 'done' entry was silently created (ledger file absent or contains no done entry)
    const ledgerFile = path.join(tmpDir, 'FTR-999-token-ledger.json');
    if (fs.existsSync(ledgerFile)) {
      const afterEntries = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
      const hasDone = afterEntries.some(function (e) { return e.status === 'done'; });
      expect(hasDone).toBe(false);
    }
  });
});

// ---------------------------------------------------------------------------
// fail
// ---------------------------------------------------------------------------

describe('execution-ledger — fail', () => {
  let tmpDir;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'led-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('marks an open entry as failed and records completed_at', () => {
    // Arrange
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');
    ledger.open(tmpDir, prefix, 'test-agent', 'phase1', 'haiku', 1);

    // Act
    ledger.fail(tmpDir, prefix, 'test-agent', null, 1);

    // Assert
    const entries = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    expect(entries[0].status).toBe('failed');
    expect(entries[0].completed_at).toBeTruthy();
  });

  it('stores a sanitized error field when an error is supplied', () => {
    // Arrange
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');
    ledger.open(tmpDir, prefix, 'test-agent', 'phase1', 'haiku', 1);

    // Act: pass an error string that contains a newline
    ledger.fail(tmpDir, prefix, 'test-agent', 'boom\nsecond line', 1);

    // Assert: status is failed with completed_at
    const entries = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    expect(entries[0].status).toBe('failed');
    expect(entries[0].completed_at).toBeTruthy();
    // Assert: error is sanitized — contains the original text but no newline
    expect(entries[0].error).toContain('boom');
    expect(entries[0].error).not.toMatch(/\n/);
  });

  it('works without an error argument (error field absent or null)', () => {
    // Arrange
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');
    ledger.open(tmpDir, prefix, 'test-agent', 'phase1', 'haiku', 1);

    // Act: omit the error argument
    ledger.fail(tmpDir, prefix, 'test-agent', undefined, 1);

    // Assert: status is failed with completed_at; no error field stored
    const entries = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    expect(entries[0].status).toBe('failed');
    expect(entries[0].completed_at).toBeTruthy();
    expect(entries[0].error).toBeUndefined();
  });

  it('throws for a never-opened operation without creating an entry', () => {
    // Arrange: fresh empty dir (set up in beforeEach); no open() call made

    // Act & Assert: fail must throw when no entry has ever been opened
    expect(() => ledger.fail(tmpDir, 'FTR-999', 'ghost', 'x', 1)).toThrow();

    // Assert: no 'failed' entry was silently created (file absent or has no failed entry)
    const ledgerFile = path.join(tmpDir, 'FTR-999-token-ledger.json');
    if (fs.existsSync(ledgerFile)) {
      const afterEntries = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
      const hasFailed = afterEntries.some(function (e) { return e.status === 'failed'; });
      expect(hasFailed).toBe(false);
    }
  });
});

// ---------------------------------------------------------------------------
// skip
// ---------------------------------------------------------------------------

describe('execution-ledger — skip', () => {
  let tmpDir;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'led-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('creates a terminal skipped entry when none exists', () => {
    // Arrange: tmpDir is a fresh empty directory (set up in beforeEach)
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');

    // Act: skip on an empty ledger (no prior open)
    ledger.skip(tmpDir, prefix, 'a', 'p', 'haiku', 1);

    // Assert: exactly one entry created with terminal skipped state
    const entries = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    expect(entries).toHaveLength(1);
    expect(entries[0].status).toBe('skipped');
    expect(entries[0].started_at).toBe(entries[0].completed_at);
    expect(entries[0].phase_delta_tokens).toBeNull();
    expect(entries[0].phase).toBe('p');
    expect(entries[0].model).toBe('haiku');
  });

  it.todo('started_at equals completed_at on a freshly created skip entry');

  it('updates an existing entry in place when exactly one match exists, preserving started_at', () => {
    // Arrange: open an entry so exactly one match exists in the ledger
    const prefix          = 'FTR-999';
    const ledgerFile      = path.join(tmpDir, prefix + '-token-ledger.json');
    ledger.open(tmpDir, prefix, 'test-agent', 'phase1', 'haiku', 1);
    const openedEntries   = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    const capturedStartedAt = openedEntries[0].started_at;

    // Act: skip the same agent/attempt (exact operation_id match)
    ledger.skip(tmpDir, prefix, 'test-agent', 'phase1', 'haiku', 1);

    // Assert: still exactly one entry; status updated; started_at preserved; completed_at present
    const entries = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    expect(entries).toHaveLength(1);
    expect(entries[0].status).toBe('skipped');
    expect(entries[0].started_at).toBe(capturedStartedAt);
    expect(entries[0].completed_at).toBeTruthy();
  });

  it.todo('preserves started_at when updating an existing entry in place');

  it('throws on ambiguous agent fallback matching multiple entries', () => {
    // Arrange: open two entries for the same agent under different attempts so the
    // agent-name fallback has 2 matches, and use attempt=99 (no exact operation_id hit)
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');
    ledger.open(tmpDir, prefix, 'multi-agent', 'phase1', 'haiku', 1);
    ledger.open(tmpDir, prefix, 'multi-agent', 'phase1', 'haiku', 2);
    const entriesBefore = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));

    // Act & Assert: skip with a non-matching attempt (99) triggers ambiguous fallback → throws
    expect(() => ledger.skip(tmpDir, prefix, 'multi-agent', 'phase1', 'haiku', 99)).toThrow();

    // Assert: no additional or mutated skipped entry was written
    const entriesAfter = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    expect(entriesAfter).toHaveLength(entriesBefore.length);
    const hasSkipped = entriesAfter.some(function (e) { return e.status === 'skipped'; });
    expect(hasSkipped).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// locking
// ---------------------------------------------------------------------------

describe('execution-ledger — locking', () => {
  it.todo('_acquireLock creates a lock file with O_EXCL owner token (pid, startedAt, nonce)');
  it.todo('a second _acquireLock call times out when the lock is already held');
  it.todo('_releaseLock unlinks the lock file only when the nonce still matches (ABA-safe)');
  it.todo('a stale lock (age > 30s AND owner not alive) is reclaimed by a subsequent acquire');
  it.todo('an orphan lock is reclaimed only once file-mtime age exceeds the orphan threshold');
  it.todo('a younger malformed lock is waited on rather than force-deleted');
});

// ---------------------------------------------------------------------------
// legacy compatibility
// ---------------------------------------------------------------------------

describe('execution-ledger — legacy compatibility', () => {
  it.todo('entries lacking operation_id are matched via unambiguous agent fallback');
  it.todo('unknown or legacy fields are preserved verbatim on update');
  it.todo('a real FTR-014 ledger fixture parses and updates without data loss');
  it.todo('no auto-migration of unrelated legacy values occurs');
});

// ---------------------------------------------------------------------------
// resume / idempotency (US-07)
// ---------------------------------------------------------------------------

describe('execution-ledger — resume / idempotency', () => {
  let tmpDir;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'led-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('re-opening the same operation_id produces no duplicate entry', () => {
    // Arrange: open an entry for a well-known (prefix, agent, attempt) triple
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');
    ledger.open(tmpDir, prefix, 'resume-agent', 'phase1', 'haiku', 1);

    // Act: open the same triple again (resume)
    ledger.open(tmpDir, prefix, 'resume-agent', 'phase1', 'haiku', 1);

    // Assert: exactly one entry, status is running — no duplicate appended
    const entries = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    expect(entries).toHaveLength(1);
    expect(entries[0].status).toBe('running');
  });

  it('resume preserves the original started_at timestamp', () => {
    // Arrange: first open — capture the started_at it writes
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');
    ledger.open(tmpDir, prefix, 'resume-agent', 'phase1', 'haiku', 1);
    const originalStartedAt = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'))[0].started_at;

    // Act: re-open (resume) — must NOT update started_at
    ledger.open(tmpDir, prefix, 'resume-agent', 'phase1', 'haiku', 1);

    // Assert: started_at is unchanged after the resume
    const entries = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    expect(entries[0].started_at).toBe(originalStartedAt);
  });

  it('positive phase_delta_tokens survives a close with tokens omitted after resume', () => {
    // Arrange: open an entry, then seed a positive phase_delta_tokens on it
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');
    ledger.open(tmpDir, prefix, 'resume-agent', 'phase1', 'haiku', 1);
    const seeded = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    seeded[0].phase_delta_tokens = 4321;
    ledger._writeLedger(ledgerFile, seeded);

    // Act: resume (re-open preserves tokens), then close without supplying tokens
    ledger.open(tmpDir, prefix, 'resume-agent', 'phase1', 'haiku', 1);
    ledger.close(tmpDir, prefix, 'resume-agent', null, 1);

    // Assert: the positive token count survived the full resume+close cycle
    const entries = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    expect(entries[0].phase_delta_tokens).toBe(4321);
    expect(entries[0].status).toBe('done');
  });

  it('exactly one entry remains after an open-resume-close cycle for the same operation_id', () => {
    // Arrange / Act: open → resume (re-open) → close — all for the same triple
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');
    ledger.open(tmpDir, prefix, 'cycle-agent', 'phase1', 'haiku', 1);
    ledger.open(tmpDir, prefix, 'cycle-agent', 'phase1', 'haiku', 1); // resume
    ledger.close(tmpDir, prefix, 'cycle-agent', null, 1);

    // Assert: exactly one entry total, status done — no phantom entries created
    const entries = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    expect(entries).toHaveLength(1);
    expect(entries[0].status).toBe('done');
  });
});

// ---------------------------------------------------------------------------
// rework / US-08
// ---------------------------------------------------------------------------

describe('execution-ledger — rework / US-08', () => {
  let tmpDir;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'led-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('rework attempt yields a distinct operation_id from the original attempt', () => {
    // Arrange: open attempt 1
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');
    ledger.open(tmpDir, prefix, 'rework-agent', 'phase1', 'haiku', 1);

    // Act: open the same agent at attempt 2 (rework)
    ledger.open(tmpDir, prefix, 'rework-agent', 'phase1', 'haiku', 2);

    // Assert: the computed ids for attempt 1 and attempt 2 are distinct
    const id1 = ledger.computeOperationId(prefix, 'rework-agent', 1);
    const id2 = ledger.computeOperationId(prefix, 'rework-agent', 2);
    expect(id1).not.toBe(id2);

    // Assert: both entries exist in the ledger with their respective distinct ids
    const entries = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    const entry1  = entries.find(function (e) { return e.operation_id === id1; });
    const entry2  = entries.find(function (e) { return e.operation_id === id2; });
    expect(entry1).toBeDefined();
    expect(entry2).toBeDefined();
  });

  it('rework attempt leaves the original attempt-1 entry untouched (operation_id and started_at unchanged)', () => {
    // Arrange: open attempt 1 and capture its operation_id and started_at
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');
    ledger.open(tmpDir, prefix, 'rework-agent', 'phase1', 'haiku', 1);
    const originalEntries   = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    const originalOpId      = originalEntries[0].operation_id;
    const originalStartedAt = originalEntries[0].started_at;

    // Act: open attempt 2 (rework) for the same agent
    ledger.open(tmpDir, prefix, 'rework-agent', 'phase1', 'haiku', 2);

    // Assert: the original attempt-1 entry is still present with operation_id and started_at unchanged
    const afterEntries  = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    const attempt1Entry = afterEntries.find(function (e) { return e.operation_id === originalOpId; });
    expect(attempt1Entry).toBeDefined();
    expect(attempt1Entry.operation_id).toBe(originalOpId);
    expect(attempt1Entry.started_at).toBe(originalStartedAt);
  });

  it('ledger has two entries both correlatable by agent key with distinct operation_ids after a rework attempt', () => {
    // Arrange
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');

    // Act: open attempt 1 then attempt 2 (rework) for the same agent
    ledger.open(tmpDir, prefix, 'rework-agent', 'phase1', 'haiku', 1);
    ledger.open(tmpDir, prefix, 'rework-agent', 'phase1', 'haiku', 2);

    // Assert: exactly two entries, both sharing the same agent key, with distinct operation_ids
    const entries = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    expect(entries).toHaveLength(2);
    const allSameAgent = entries.every(function (e) { return e.agent === 'rework-agent'; });
    expect(allSameAgent).toBe(true);
    expect(entries[0].operation_id).not.toBe(entries[1].operation_id);
  });

  it('agent slug collision resistance: a:b, a/b, a-b produce three distinct operation_ids', () => {
    // Arrange: three slugs that collapse under naive concatenation
    const prefix  = 'FTR-999';
    const attempt = 1;

    // Act: compute ids for each slug
    const idColon  = ledger.computeOperationId(prefix, 'a:b', attempt);
    const idSlash  = ledger.computeOperationId(prefix, 'a/b', attempt);
    const idHyphen = ledger.computeOperationId(prefix, 'a-b', attempt);

    // Assert: all three are pairwise distinct (JSON.stringify-of-array avoids collision)
    expect(idColon).not.toBe(idSlash);
    expect(idColon).not.toBe(idHyphen);
    expect(idSlash).not.toBe(idHyphen);
  });

  it('computeOperationId is deterministic: same tuple always yields the same id', () => {
    // Arrange
    const prefix  = 'FTR-999';
    const agent   = 'deterministic-agent';
    const attempt = 3;

    // Act: call twice with an identical tuple
    const id1 = ledger.computeOperationId(prefix, agent, attempt);
    const id2 = ledger.computeOperationId(prefix, agent, attempt);

    // Assert: identical output for identical input (pure hash, no randomness)
    expect(id1).toBe(id2);
  });
});

// ---------------------------------------------------------------------------
// concurrency
// ---------------------------------------------------------------------------

describe('execution-ledger — concurrency', () => {
  it.todo('two concurrent open() calls serialize via the cross-process lock');
  it.todo('both updates are present in the ledger with no lost update');
  it.todo('each concurrent entry carries correct data after serialization');
});

// ---------------------------------------------------------------------------
// malformed/corrupt ledger
// ---------------------------------------------------------------------------

describe('execution-ledger — malformed/corrupt ledger', () => {
  let tmpDir;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'led-'));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('throws CORRUPT_LEDGER code when open() encounters a malformed JSON ledger', () => {
    // Arrange: write a malformed (unparseable, non-empty) JSON ledger
    const prefix     = 'FTR-999';
    const ledgerFile = path.join(tmpDir, prefix + '-token-ledger.json');
    fs.writeFileSync(ledgerFile, '{not valid json');

    // Act: capture the thrown error so we can inspect its code
    let caughtErr;
    try {
      ledger.open(tmpDir, prefix, 'test-agent', 'phase1', 'haiku', 1);
    } catch (e) {
      caughtErr = e;
    }

    // Assert: an error was thrown
    expect(caughtErr).toBeDefined();
    // Assert: the error carries the CORRUPT_LEDGER code (fail-closed contract)
    expect(caughtErr.code).toBe('CORRUPT_LEDGER');
  });

  it('creates a backup sidecar containing the original corrupt bytes', () => {
    // Arrange: write a malformed JSON ledger
    const prefix         = 'FTR-999';
    const ledgerFile     = path.join(tmpDir, prefix + '-token-ledger.json');
    const corruptContent = '{not valid json';
    fs.writeFileSync(ledgerFile, corruptContent);

    // Act: trigger the corrupt-ledger detection path
    try { ledger.open(tmpDir, prefix, 'test-agent', 'phase1', 'haiku', 1); } catch (_) {}

    // Assert: a sidecar file whose name contains 'backup' was created in the same directory
    const files    = fs.readdirSync(tmpDir);
    const hasSidecar = files.some(function (n) { return n.includes('backup'); });
    expect(hasSidecar).toBe(true);

    // Assert: the sidecar content exactly equals the original corrupt bytes (recoverable)
    const sidecarName    = files.find(function (n) { return n.includes('backup'); });
    const sidecarContent = fs.readFileSync(path.join(tmpDir, sidecarName), 'utf8');
    expect(sidecarContent).toBe(corruptContent);
  });

  it('does not overwrite the original malformed ledger file', () => {
    // Arrange: write a malformed JSON ledger
    const prefix         = 'FTR-999';
    const ledgerFile     = path.join(tmpDir, prefix + '-token-ledger.json');
    const corruptContent = '{not valid json';
    fs.writeFileSync(ledgerFile, corruptContent);

    // Act: trigger the corrupt-ledger detection path
    try { ledger.open(tmpDir, prefix, 'test-agent', 'phase1', 'haiku', 1); } catch (_) {}

    // Assert: the original ledger file bytes are unchanged
    const afterContent = fs.readFileSync(ledgerFile, 'utf8');
    expect(afterContent).toBe(corruptContent);
  });

  it('does not silently create a fresh empty ledger after a malformed-ledger failure', () => {
    // Arrange: write a malformed JSON ledger
    const prefix         = 'FTR-999';
    const ledgerFile     = path.join(tmpDir, prefix + '-token-ledger.json');
    const corruptContent = '{not valid json';
    fs.writeFileSync(ledgerFile, corruptContent);

    // Act: trigger the corrupt-ledger detection path
    try { ledger.open(tmpDir, prefix, 'test-agent', 'phase1', 'haiku', 1); } catch (_) {}

    // Assert: the ledger file still contains the malformed bytes, not a fresh valid JSON array
    const afterContent = fs.readFileSync(ledgerFile, 'utf8');
    expect(afterContent).toBe(corruptContent);
    // Assert: content remains unparseable — no silent replacement with [] or a new running entry
    expect(() => JSON.parse(afterContent)).toThrow();
  });

  it('fail-closed: close() also throws and leaves the corrupt file untouched', () => {
    // Arrange: write a malformed JSON ledger at the conventional path
    const prefix         = 'FTR-999';
    const ledgerFile     = path.join(tmpDir, prefix + '-token-ledger.json');
    const corruptContent = '{not valid json';
    fs.writeFileSync(ledgerFile, corruptContent);

    // Act & Assert: close() throws — the fail-closed contract applies to every write operation
    expect(() => ledger.close(tmpDir, prefix, 'test-agent', null, 1)).toThrow();

    // Assert: the original corrupt bytes are preserved (no silent overwrite occurred)
    expect(fs.readFileSync(ledgerFile, 'utf8')).toBe(corruptContent);
  });
});
